### PR TITLE
Feature/gapdc 25

### PR DESCRIPTION
**Pull request by televisedbrain**
Initialise sample service and repository workflows

### CODE REVIEW

**Comment by televisedbrain** [comment]
Fixing github secret so linter can push changes - the pipeline will succeed after

**Review by sainab-omar — APPROVED** [review]
Looks good 👍

**Review by Hira-Naveed — APPROVED** [review]
Looking fab!

**Review by ellisrichardj — APPROVED** [review]
Great to get this started

**Review by praveenmurugan101 — APPROVED** [review]
Looks interesting!⭐

**Pull request merged**
